// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: primary_bean.proto

package com.ronrytest.protobuf;

public final class PrimaryBeanProtos {
  private PrimaryBeanProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PrimaryBeanOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string email = 1;
    /**
     * <code>optional string email = 1;</code>
     */
    boolean hasEmail();
    /**
     * <code>optional string email = 1;</code>
     */
    java.lang.String getEmail();
    /**
     * <code>optional string email = 1;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    // optional string mobile = 2;
    /**
     * <code>optional string mobile = 2;</code>
     */
    boolean hasMobile();
    /**
     * <code>optional string mobile = 2;</code>
     */
    java.lang.String getMobile();
    /**
     * <code>optional string mobile = 2;</code>
     */
    com.google.protobuf.ByteString
        getMobileBytes();

    // optional string hashedPassword = 3;
    /**
     * <code>optional string hashedPassword = 3;</code>
     */
    boolean hasHashedPassword();
    /**
     * <code>optional string hashedPassword = 3;</code>
     */
    java.lang.String getHashedPassword();
    /**
     * <code>optional string hashedPassword = 3;</code>
     */
    com.google.protobuf.ByteString
        getHashedPasswordBytes();

    // repeated string zhiwu = 5;
    /**
     * <code>repeated string zhiwu = 5;</code>
     *
     * <pre>
     * optional DateEntity lastLoginTime = 4;
     * </pre>
     */
    java.util.List<java.lang.String>
    getZhiwuList();
    /**
     * <code>repeated string zhiwu = 5;</code>
     *
     * <pre>
     * optional DateEntity lastLoginTime = 4;
     * </pre>
     */
    int getZhiwuCount();
    /**
     * <code>repeated string zhiwu = 5;</code>
     *
     * <pre>
     * optional DateEntity lastLoginTime = 4;
     * </pre>
     */
    java.lang.String getZhiwu(int index);
    /**
     * <code>repeated string zhiwu = 5;</code>
     *
     * <pre>
     * optional DateEntity lastLoginTime = 4;
     * </pre>
     */
    com.google.protobuf.ByteString
        getZhiwuBytes(int index);

    // repeated int32 gonghao = 6;
    /**
     * <code>repeated int32 gonghao = 6;</code>
     */
    java.util.List<java.lang.Integer> getGonghaoList();
    /**
     * <code>repeated int32 gonghao = 6;</code>
     */
    int getGonghaoCount();
    /**
     * <code>repeated int32 gonghao = 6;</code>
     */
    int getGonghao(int index);

    // repeated string shouru = 7;
    /**
     * <code>repeated string shouru = 7;</code>
     */
    java.util.List<java.lang.String>
    getShouruList();
    /**
     * <code>repeated string shouru = 7;</code>
     */
    int getShouruCount();
    /**
     * <code>repeated string shouru = 7;</code>
     */
    java.lang.String getShouru(int index);
    /**
     * <code>repeated string shouru = 7;</code>
     */
    com.google.protobuf.ByteString
        getShouruBytes(int index);
  }
  /**
   * Protobuf type {@code com.ronrytest.protobuffer.PrimaryBean}
   */
  public static final class PrimaryBean extends
      com.google.protobuf.GeneratedMessage
      implements PrimaryBeanOrBuilder {
    // Use PrimaryBean.newBuilder() to construct.
    private PrimaryBean(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PrimaryBean(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PrimaryBean defaultInstance;
    public static PrimaryBean getDefaultInstance() {
      return defaultInstance;
    }

    public PrimaryBean getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PrimaryBean(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              email_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              mobile_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              hashedPassword_ = input.readBytes();
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                zhiwu_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              zhiwu_.add(input.readBytes());
              break;
            }
            case 48: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                gonghao_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000010;
              }
              gonghao_.add(input.readInt32());
              break;
            }
            case 50: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010) && input.getBytesUntilLimit() > 0) {
                gonghao_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000010;
              }
              while (input.getBytesUntilLimit() > 0) {
                gonghao_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                shouru_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000020;
              }
              shouru_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          zhiwu_ = new com.google.protobuf.UnmodifiableLazyStringList(zhiwu_);
        }
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          gonghao_ = java.util.Collections.unmodifiableList(gonghao_);
        }
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          shouru_ = new com.google.protobuf.UnmodifiableLazyStringList(shouru_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ronrytest.protobuf.PrimaryBeanProtos.internal_static_com_ronrytest_protobuffer_PrimaryBean_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ronrytest.protobuf.PrimaryBeanProtos.internal_static_com_ronrytest_protobuffer_PrimaryBean_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ronrytest.protobuf.PrimaryBeanProtos.PrimaryBean.class, com.ronrytest.protobuf.PrimaryBeanProtos.PrimaryBean.Builder.class);
    }

    public static com.google.protobuf.Parser<PrimaryBean> PARSER =
        new com.google.protobuf.AbstractParser<PrimaryBean>() {
      public PrimaryBean parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PrimaryBean(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PrimaryBean> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string email = 1;
    public static final int EMAIL_FIELD_NUMBER = 1;
    private java.lang.Object email_;
    /**
     * <code>optional string email = 1;</code>
     */
    public boolean hasEmail() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string email = 1;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          email_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string email = 1;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string mobile = 2;
    public static final int MOBILE_FIELD_NUMBER = 2;
    private java.lang.Object mobile_;
    /**
     * <code>optional string mobile = 2;</code>
     */
    public boolean hasMobile() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string mobile = 2;</code>
     */
    public java.lang.String getMobile() {
      java.lang.Object ref = mobile_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          mobile_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string mobile = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMobileBytes() {
      java.lang.Object ref = mobile_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mobile_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string hashedPassword = 3;
    public static final int HASHEDPASSWORD_FIELD_NUMBER = 3;
    private java.lang.Object hashedPassword_;
    /**
     * <code>optional string hashedPassword = 3;</code>
     */
    public boolean hasHashedPassword() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string hashedPassword = 3;</code>
     */
    public java.lang.String getHashedPassword() {
      java.lang.Object ref = hashedPassword_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          hashedPassword_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string hashedPassword = 3;</code>
     */
    public com.google.protobuf.ByteString
        getHashedPasswordBytes() {
      java.lang.Object ref = hashedPassword_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hashedPassword_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated string zhiwu = 5;
    public static final int ZHIWU_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList zhiwu_;
    /**
     * <code>repeated string zhiwu = 5;</code>
     *
     * <pre>
     * optional DateEntity lastLoginTime = 4;
     * </pre>
     */
    public java.util.List<java.lang.String>
        getZhiwuList() {
      return zhiwu_;
    }
    /**
     * <code>repeated string zhiwu = 5;</code>
     *
     * <pre>
     * optional DateEntity lastLoginTime = 4;
     * </pre>
     */
    public int getZhiwuCount() {
      return zhiwu_.size();
    }
    /**
     * <code>repeated string zhiwu = 5;</code>
     *
     * <pre>
     * optional DateEntity lastLoginTime = 4;
     * </pre>
     */
    public java.lang.String getZhiwu(int index) {
      return zhiwu_.get(index);
    }
    /**
     * <code>repeated string zhiwu = 5;</code>
     *
     * <pre>
     * optional DateEntity lastLoginTime = 4;
     * </pre>
     */
    public com.google.protobuf.ByteString
        getZhiwuBytes(int index) {
      return zhiwu_.getByteString(index);
    }

    // repeated int32 gonghao = 6;
    public static final int GONGHAO_FIELD_NUMBER = 6;
    private java.util.List<java.lang.Integer> gonghao_;
    /**
     * <code>repeated int32 gonghao = 6;</code>
     */
    public java.util.List<java.lang.Integer>
        getGonghaoList() {
      return gonghao_;
    }
    /**
     * <code>repeated int32 gonghao = 6;</code>
     */
    public int getGonghaoCount() {
      return gonghao_.size();
    }
    /**
     * <code>repeated int32 gonghao = 6;</code>
     */
    public int getGonghao(int index) {
      return gonghao_.get(index);
    }

    // repeated string shouru = 7;
    public static final int SHOURU_FIELD_NUMBER = 7;
    private com.google.protobuf.LazyStringList shouru_;
    /**
     * <code>repeated string shouru = 7;</code>
     */
    public java.util.List<java.lang.String>
        getShouruList() {
      return shouru_;
    }
    /**
     * <code>repeated string shouru = 7;</code>
     */
    public int getShouruCount() {
      return shouru_.size();
    }
    /**
     * <code>repeated string shouru = 7;</code>
     */
    public java.lang.String getShouru(int index) {
      return shouru_.get(index);
    }
    /**
     * <code>repeated string shouru = 7;</code>
     */
    public com.google.protobuf.ByteString
        getShouruBytes(int index) {
      return shouru_.getByteString(index);
    }

    private void initFields() {
      email_ = "";
      mobile_ = "";
      hashedPassword_ = "";
      zhiwu_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      gonghao_ = java.util.Collections.emptyList();
      shouru_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getEmailBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMobileBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getHashedPasswordBytes());
      }
      for (int i = 0; i < zhiwu_.size(); i++) {
        output.writeBytes(5, zhiwu_.getByteString(i));
      }
      for (int i = 0; i < gonghao_.size(); i++) {
        output.writeInt32(6, gonghao_.get(i));
      }
      for (int i = 0; i < shouru_.size(); i++) {
        output.writeBytes(7, shouru_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getEmailBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMobileBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getHashedPasswordBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < zhiwu_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(zhiwu_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getZhiwuList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < gonghao_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(gonghao_.get(i));
        }
        size += dataSize;
        size += 1 * getGonghaoList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < shouru_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(shouru_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getShouruList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.ronrytest.protobuf.PrimaryBeanProtos.PrimaryBean parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ronrytest.protobuf.PrimaryBeanProtos.PrimaryBean parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ronrytest.protobuf.PrimaryBeanProtos.PrimaryBean parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ronrytest.protobuf.PrimaryBeanProtos.PrimaryBean parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ronrytest.protobuf.PrimaryBeanProtos.PrimaryBean parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ronrytest.protobuf.PrimaryBeanProtos.PrimaryBean parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.ronrytest.protobuf.PrimaryBeanProtos.PrimaryBean parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.ronrytest.protobuf.PrimaryBeanProtos.PrimaryBean parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.ronrytest.protobuf.PrimaryBeanProtos.PrimaryBean parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ronrytest.protobuf.PrimaryBeanProtos.PrimaryBean parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ronrytest.protobuf.PrimaryBeanProtos.PrimaryBean prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ronrytest.protobuffer.PrimaryBean}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.ronrytest.protobuf.PrimaryBeanProtos.PrimaryBeanOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ronrytest.protobuf.PrimaryBeanProtos.internal_static_com_ronrytest_protobuffer_PrimaryBean_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ronrytest.protobuf.PrimaryBeanProtos.internal_static_com_ronrytest_protobuffer_PrimaryBean_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ronrytest.protobuf.PrimaryBeanProtos.PrimaryBean.class, com.ronrytest.protobuf.PrimaryBeanProtos.PrimaryBean.Builder.class);
      }

      // Construct using com.ronrytest.protobuffer.PrimaryBeanProtos.PrimaryBean.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        email_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        mobile_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        hashedPassword_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        zhiwu_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        gonghao_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        shouru_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ronrytest.protobuf.PrimaryBeanProtos.internal_static_com_ronrytest_protobuffer_PrimaryBean_descriptor;
      }

      public com.ronrytest.protobuf.PrimaryBeanProtos.PrimaryBean getDefaultInstanceForType() {
        return com.ronrytest.protobuf.PrimaryBeanProtos.PrimaryBean.getDefaultInstance();
      }

      public com.ronrytest.protobuf.PrimaryBeanProtos.PrimaryBean build() {
        com.ronrytest.protobuf.PrimaryBeanProtos.PrimaryBean result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ronrytest.protobuf.PrimaryBeanProtos.PrimaryBean buildPartial() {
        com.ronrytest.protobuf.PrimaryBeanProtos.PrimaryBean result = new com.ronrytest.protobuf.PrimaryBeanProtos.PrimaryBean(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.email_ = email_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.mobile_ = mobile_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.hashedPassword_ = hashedPassword_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          zhiwu_ = new com.google.protobuf.UnmodifiableLazyStringList(
              zhiwu_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.zhiwu_ = zhiwu_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          gonghao_ = java.util.Collections.unmodifiableList(gonghao_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.gonghao_ = gonghao_;
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          shouru_ = new com.google.protobuf.UnmodifiableLazyStringList(
              shouru_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.shouru_ = shouru_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ronrytest.protobuf.PrimaryBeanProtos.PrimaryBean) {
          return mergeFrom((com.ronrytest.protobuf.PrimaryBeanProtos.PrimaryBean)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ronrytest.protobuf.PrimaryBeanProtos.PrimaryBean other) {
        if (other == com.ronrytest.protobuf.PrimaryBeanProtos.PrimaryBean.getDefaultInstance()) return this;
        if (other.hasEmail()) {
          bitField0_ |= 0x00000001;
          email_ = other.email_;
          onChanged();
        }
        if (other.hasMobile()) {
          bitField0_ |= 0x00000002;
          mobile_ = other.mobile_;
          onChanged();
        }
        if (other.hasHashedPassword()) {
          bitField0_ |= 0x00000004;
          hashedPassword_ = other.hashedPassword_;
          onChanged();
        }
        if (!other.zhiwu_.isEmpty()) {
          if (zhiwu_.isEmpty()) {
            zhiwu_ = other.zhiwu_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureZhiwuIsMutable();
            zhiwu_.addAll(other.zhiwu_);
          }
          onChanged();
        }
        if (!other.gonghao_.isEmpty()) {
          if (gonghao_.isEmpty()) {
            gonghao_ = other.gonghao_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureGonghaoIsMutable();
            gonghao_.addAll(other.gonghao_);
          }
          onChanged();
        }
        if (!other.shouru_.isEmpty()) {
          if (shouru_.isEmpty()) {
            shouru_ = other.shouru_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureShouruIsMutable();
            shouru_.addAll(other.shouru_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ronrytest.protobuf.PrimaryBeanProtos.PrimaryBean parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ronrytest.protobuf.PrimaryBeanProtos.PrimaryBean) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string email = 1;
      private java.lang.Object email_ = "";
      /**
       * <code>optional string email = 1;</code>
       */
      public boolean hasEmail() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string email = 1;</code>
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string email = 1;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string email = 1;</code>
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string email = 1;</code>
       */
      public Builder clearEmail() {
        bitField0_ = (bitField0_ & ~0x00000001);
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>optional string email = 1;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        email_ = value;
        onChanged();
        return this;
      }

      // optional string mobile = 2;
      private java.lang.Object mobile_ = "";
      /**
       * <code>optional string mobile = 2;</code>
       */
      public boolean hasMobile() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string mobile = 2;</code>
       */
      public java.lang.String getMobile() {
        java.lang.Object ref = mobile_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          mobile_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string mobile = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMobileBytes() {
        java.lang.Object ref = mobile_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mobile_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string mobile = 2;</code>
       */
      public Builder setMobile(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        mobile_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string mobile = 2;</code>
       */
      public Builder clearMobile() {
        bitField0_ = (bitField0_ & ~0x00000002);
        mobile_ = getDefaultInstance().getMobile();
        onChanged();
        return this;
      }
      /**
       * <code>optional string mobile = 2;</code>
       */
      public Builder setMobileBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        mobile_ = value;
        onChanged();
        return this;
      }

      // optional string hashedPassword = 3;
      private java.lang.Object hashedPassword_ = "";
      /**
       * <code>optional string hashedPassword = 3;</code>
       */
      public boolean hasHashedPassword() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string hashedPassword = 3;</code>
       */
      public java.lang.String getHashedPassword() {
        java.lang.Object ref = hashedPassword_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          hashedPassword_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string hashedPassword = 3;</code>
       */
      public com.google.protobuf.ByteString
          getHashedPasswordBytes() {
        java.lang.Object ref = hashedPassword_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hashedPassword_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string hashedPassword = 3;</code>
       */
      public Builder setHashedPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        hashedPassword_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string hashedPassword = 3;</code>
       */
      public Builder clearHashedPassword() {
        bitField0_ = (bitField0_ & ~0x00000004);
        hashedPassword_ = getDefaultInstance().getHashedPassword();
        onChanged();
        return this;
      }
      /**
       * <code>optional string hashedPassword = 3;</code>
       */
      public Builder setHashedPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        hashedPassword_ = value;
        onChanged();
        return this;
      }

      // repeated string zhiwu = 5;
      private com.google.protobuf.LazyStringList zhiwu_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureZhiwuIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          zhiwu_ = new com.google.protobuf.LazyStringArrayList(zhiwu_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string zhiwu = 5;</code>
       *
       * <pre>
       * optional DateEntity lastLoginTime = 4;
       * </pre>
       */
      public java.util.List<java.lang.String>
          getZhiwuList() {
        return java.util.Collections.unmodifiableList(zhiwu_);
      }
      /**
       * <code>repeated string zhiwu = 5;</code>
       *
       * <pre>
       * optional DateEntity lastLoginTime = 4;
       * </pre>
       */
      public int getZhiwuCount() {
        return zhiwu_.size();
      }
      /**
       * <code>repeated string zhiwu = 5;</code>
       *
       * <pre>
       * optional DateEntity lastLoginTime = 4;
       * </pre>
       */
      public java.lang.String getZhiwu(int index) {
        return zhiwu_.get(index);
      }
      /**
       * <code>repeated string zhiwu = 5;</code>
       *
       * <pre>
       * optional DateEntity lastLoginTime = 4;
       * </pre>
       */
      public com.google.protobuf.ByteString
          getZhiwuBytes(int index) {
        return zhiwu_.getByteString(index);
      }
      /**
       * <code>repeated string zhiwu = 5;</code>
       *
       * <pre>
       * optional DateEntity lastLoginTime = 4;
       * </pre>
       */
      public Builder setZhiwu(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureZhiwuIsMutable();
        zhiwu_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string zhiwu = 5;</code>
       *
       * <pre>
       * optional DateEntity lastLoginTime = 4;
       * </pre>
       */
      public Builder addZhiwu(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureZhiwuIsMutable();
        zhiwu_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string zhiwu = 5;</code>
       *
       * <pre>
       * optional DateEntity lastLoginTime = 4;
       * </pre>
       */
      public Builder addAllZhiwu(
          java.lang.Iterable<java.lang.String> values) {
        ensureZhiwuIsMutable();
        super.addAll(values, zhiwu_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string zhiwu = 5;</code>
       *
       * <pre>
       * optional DateEntity lastLoginTime = 4;
       * </pre>
       */
      public Builder clearZhiwu() {
        zhiwu_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string zhiwu = 5;</code>
       *
       * <pre>
       * optional DateEntity lastLoginTime = 4;
       * </pre>
       */
      public Builder addZhiwuBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureZhiwuIsMutable();
        zhiwu_.add(value);
        onChanged();
        return this;
      }

      // repeated int32 gonghao = 6;
      private java.util.List<java.lang.Integer> gonghao_ = java.util.Collections.emptyList();
      private void ensureGonghaoIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          gonghao_ = new java.util.ArrayList<java.lang.Integer>(gonghao_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated int32 gonghao = 6;</code>
       */
      public java.util.List<java.lang.Integer>
          getGonghaoList() {
        return java.util.Collections.unmodifiableList(gonghao_);
      }
      /**
       * <code>repeated int32 gonghao = 6;</code>
       */
      public int getGonghaoCount() {
        return gonghao_.size();
      }
      /**
       * <code>repeated int32 gonghao = 6;</code>
       */
      public int getGonghao(int index) {
        return gonghao_.get(index);
      }
      /**
       * <code>repeated int32 gonghao = 6;</code>
       */
      public Builder setGonghao(
          int index, int value) {
        ensureGonghaoIsMutable();
        gonghao_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 gonghao = 6;</code>
       */
      public Builder addGonghao(int value) {
        ensureGonghaoIsMutable();
        gonghao_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 gonghao = 6;</code>
       */
      public Builder addAllGonghao(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureGonghaoIsMutable();
        super.addAll(values, gonghao_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 gonghao = 6;</code>
       */
      public Builder clearGonghao() {
        gonghao_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }

      // repeated string shouru = 7;
      private com.google.protobuf.LazyStringList shouru_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureShouruIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          shouru_ = new com.google.protobuf.LazyStringArrayList(shouru_);
          bitField0_ |= 0x00000020;
         }
      }
      /**
       * <code>repeated string shouru = 7;</code>
       */
      public java.util.List<java.lang.String>
          getShouruList() {
        return java.util.Collections.unmodifiableList(shouru_);
      }
      /**
       * <code>repeated string shouru = 7;</code>
       */
      public int getShouruCount() {
        return shouru_.size();
      }
      /**
       * <code>repeated string shouru = 7;</code>
       */
      public java.lang.String getShouru(int index) {
        return shouru_.get(index);
      }
      /**
       * <code>repeated string shouru = 7;</code>
       */
      public com.google.protobuf.ByteString
          getShouruBytes(int index) {
        return shouru_.getByteString(index);
      }
      /**
       * <code>repeated string shouru = 7;</code>
       */
      public Builder setShouru(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureShouruIsMutable();
        shouru_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string shouru = 7;</code>
       */
      public Builder addShouru(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureShouruIsMutable();
        shouru_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string shouru = 7;</code>
       */
      public Builder addAllShouru(
          java.lang.Iterable<java.lang.String> values) {
        ensureShouruIsMutable();
        super.addAll(values, shouru_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string shouru = 7;</code>
       */
      public Builder clearShouru() {
        shouru_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string shouru = 7;</code>
       */
      public Builder addShouruBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureShouruIsMutable();
        shouru_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.ronrytest.protobuffer.PrimaryBean)
    }

    static {
      defaultInstance = new PrimaryBean(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.ronrytest.protobuffer.PrimaryBean)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ronrytest_protobuffer_PrimaryBean_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_ronrytest_protobuffer_PrimaryBean_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022primary_bean.proto\022\031com.ronrytest.prot" +
      "obuffer\"t\n\013PrimaryBean\022\r\n\005email\030\001 \001(\t\022\016\n" +
      "\006mobile\030\002 \001(\t\022\026\n\016hashedPassword\030\003 \001(\t\022\r\n" +
      "\005zhiwu\030\005 \003(\t\022\017\n\007gonghao\030\006 \003(\005\022\016\n\006shouru\030" +
      "\007 \003(\tB\023B\021PrimaryBeanProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_ronrytest_protobuffer_PrimaryBean_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_ronrytest_protobuffer_PrimaryBean_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_ronrytest_protobuffer_PrimaryBean_descriptor,
              new java.lang.String[] { "Email", "Mobile", "HashedPassword", "Zhiwu", "Gonghao", "Shouru", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
